export const DIMENSION_OPTIONS = [
    'Dimension C-137',
    'Post-Apocalyptic Dimension',
    'Replacement Dimension',
    'Cronenberg Dimension',
    'Fantasy Dimension',
    'Dimension 5-126',
    "Evil Rick's Target Dimension",
    'Eric Stoltz Mask Dimension',
    'Dimension J19ζ7',
    'Dimension K-83',
    'Cromulon Dimension',
    'Testicle Monster Dimension',
    'Dimension D716-B',
    'Dimension D716',
    'Dimension D99',
    'Dimension K-22',
    'Giant Telepathic Spiders Dimension',
    'unknown',
]

export const LOCATION_TYPE = [
    'Planet',
    'Cluster',
    'Space station',
    'Microverse',
    'TV',
    'Dream',
    'Dimension',
    'Menagerie',
    'Customs',
    'Game',
    'unknown',
]
